import pylab
import os.path
import SpkD_plot_v24

# Making various plots using the .hdf file generated by the Localization script

# ...where I had the files on my computer
Folder = '/home/muthmann/backup/SpikeAnalysis/'
Subfolder = 'SpkD_v26/'
HdfFolder = '/HdfFiles/'  # where the .hdf files should go
PlotFolder = 'Plots/'  # folder for plots
Files = ('P10_6Feb15_ret2_waves_raw',)  # filenames (without '_XXX.txt')
# --------------------------------------------------------------------------
if not os.path.exists(Folder+Subfolder+PlotFolder):
    os.mkdir(Folder+Subfolder+PlotFolder)
for iii in range(len(Files)):
    PlotFile = Folder+Subfolder+PlotFolder+Files[iii]
    HdfFile = Folder+Subfolder+HdfFolder+Files[iii]+'_v28.hdf5'

    # Rasterplot
    SpkD_plot_v24.Rasterplot(HdfFile,
                             FileName=PlotFile+'_Raster_repolarizing.png',
                             FieldName='', tMin=0, tMax=20, yMin=0, yMax=64,
                             cMin=0, cMax=64, cRes=20, RepolSpikes=True,
                             LongSpikes=False, axis=0, ampThreshold=0,
                             pThreshold=0, bgColor=pylab.cm.gray(0.5),
                             SpikesCmap=pylab.cm.hot_r,
                             LongSpikesCmap=pylab.cm.cool, alpha=0.2)
    # Amplitudes
    SpkD_plot_v24.Rasterplot(HdfFile,
                             FileName=PlotFile+'_Raster_amplitudes.png',
                             FieldName='Amplitudes', tMin=0, tMax=20, yMin=0,
                             yMax=64, cMin=0, cMax=10., cRes=20,
                             RepolSpikes=True, LongSpikes=False, axis=0,
                             ampThreshold=0, pThreshold=0,
                             bgColor=pylab.cm.gray(0.5),
                             SpikesCmap=pylab.cm.hot_r,
                             LongSpikesCmap=pylab.cm.cool, alpha=0.2)

    # Scatterplot
    SpkD_plot_v24.Scatterplot(HdfFile,
                              FileName=PlotFile+'_Scatter_repolarizing.png',
                              FieldName='Amplitudes', xMin=0, xMax=64, yMin=0,
                              yMax=64, cMin=0, cMax=10, cRes=20,
                              RepolSpikes=True, LongSpikes=False,
                              ampThreshold=0, pThreshold=0,
                              bgColor=pylab.cm.gray(0.5),
                              SpikesCmap=pylab.cm.hot_r,
                              LongSpikesCmap=pylab.cm.cool, alpha=0.1)

    # Densityplot
    SpkD_plot_v24.Densityplot(HdfFile,
                              FileName=PlotFile+'_Density_repolarizing.png',
                              FieldName='', xMin=0, xMax=64, yMin=0, yMax=64,
                              cMin=10, cMax=10000, Res=8, logScale=True,
                              RepolSpikes=True, LongSpikes=False,
                              ampThreshold=0, pThreshold=0,
                              bgColor=pylab.cm.gray(0.5),
                              SpikesCmap=pylab.cm.hot_r, alpha=1.)

    # Amplitudes
    SpkD_plot_v24.Densityplot(HdfFile,
                              FileName=PlotFile+'_Density_amplitudes.png',
                              FieldName='Amplitudes', xMin=0, xMax=64, yMin=0,
                              yMax=64, cMin=0, cMax=10, Res=8, logScale=False,
                              RepolSpikes=True, LongSpikes=False,
                              ampThreshold=0, pThreshold=0,
                              bgColor=pylab.cm.gray(0.5),
                              SpikesCmap=pylab.cm.hot_r, alpha=1.)
